version: "3.1"
services:
  redmine:
    build: ./redmine
    restart: always
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: password
      RAILS_RELATIVE_URL_ROOT: /redmine
    volumes:
      - ./redmine/config/config.ru:/usr/src/redmine/config.ru

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  
  nginx:
    image: nginx:1.17.9-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/config/Redmine.conf:/etc/nginx/conf.d/Redmine.conf
    