version: "3.1"
services:
  redmine:
    image: redmine:4.1.0-alpine
    ports:
      - 8080:3000
    restart: always
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: password

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password